### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by g-loup-p** [pgrimaud/sytadin#1]
Bonjour, est-ce que votre programme prend en charge les Panneaux a Message Variable sur l'application Sytadin. Merci d'avance. Super votre programme.
🙂 Bonne journée

**Comment by pgrimaud** [comment]
Bonjour, malheureusement non.

Mais ça pourrait être une feature en plus 😄

**Comment by g-loup-p** [comment]
D'accord, merci quand même. Est-ce que vous savez si il existe un API ou qq chose d'autre pour cette fonctionnalité.

**Comment by pgrimaud** [comment]
J'avais créé ce crawler à l'époque car il n'y avait pas d'API.

Je doute qu'elle soit en place aujourd'hui, mais à vérifier...

**Comment by g-loup-p** [comment]
Après avoir regardé, je pense que c'est impossible de récupérer les messages des PMV car la fonctionnalité est seulement présente sur l'appli. Et même avec une application spécial je n'arrive pas à trouver quel requête fait l'appli & a quel serveur et d'un pts de vu légal je sais pas si c'est autorisé de faire des requêtes au serveur 😅
